name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install python-dotenv pydantic firebase-admin

      # 4️⃣ Write Firebase key to a file
      - name: Write Firebase key to file
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > serviceAccountKey.json
          echo "FIREBASE_SERVICE_ACCOUNT_KEY=serviceAccountKey.json" >> $GITHUB_ENV


      # 5️⃣ Run your tests
      - name: Run tests
        run: pytest unittests/

      # 6️⃣ (Optional) Remove Firebase key after tests for security
      - name: Delete Firebase key file
        if: always()
        run: rm -f serviceAccountKey.json
